### ISSUE TITLE
List item can be 1. instead of *

### ISSUE THREAD

**Issue by luastoned** [skoropadas/telegramify-markdown#2]
Hi, I think the [listItem](https://github.com/skoropadas/telegramify-markdown/blob/master/lib/telegramify.js#L57) function is not quite correct, as markdown lists can be

* a
* b
* c

and

1. a
2. b
3. c

Telegram will complain since the `.` after 1/2/3 is not escaped properly.

**Comment by skoropadas** [comment]
hi thanks for the feedback, I'll try to fix it today!

**Comment by luastoned** [comment]
Tables that start with `|` are also broken, as well as some random inline tags like `<!---->`

**Comment by skoropadas** [comment]
I don't have a processor for tables, because markdown of telegram doesn't support them, but as workaround, I can render them like this 
![image](https://user-images.githubusercontent.com/20700969/210232977-59076887-6d3d-49c5-b84d-a2fc00b816a0.png)

**Comment by skoropadas** [comment]
Okay, I've checked the example you left, I think I understand what you are trying to achieve, and I would say it's not really possible to convert this markdown to telegram format.
I can display a table in the telegram only via code block, as in the example above, but code block doesn't support links and other interactive elements, because it's just a code example, so it will be just a raw markdown code, that will be not really readable.

So, if you'd like to send some notifications about angular releases or something like that and use these release notes for that, then my proposal will be parse it, remove some information that cannot be displayed in telegram (like "commit" column), and convert it to markdown or to telegram markdown syntax.

**Comment by skoropadas** [comment]
Version 1.0.4 with a fix for lists has been released, so I will close the ticket for now, feel free to open it again if the issue is still reproducible, or if you have any other questions.
