### ISSUE TITLE
Cannot handle blockquotes (`>`)

### ISSUE THREAD

**Issue by RainEggplant** [skoropadas/telegramify-markdown#5]
Sorry to trouble you again. But first of all, I want to say thank you very much for developing this library! I'm currently using it with my ChatGPT Telegram bot, and most of the time it works very well, but sometimes there are small bugs that cause messages not to be parsed correctly. Really hope this can be fixed.

**Describe the bug**
Cannot handle blockquotes (`>`)

**To Reproduce**
Convert the following text:
```
> Hello
```

**Current behavior**

Did not escape `>`.

```
> Hello
```

Then Telegram will raise an error:

```
ETELEGRAM: 400 Bad Request: can't parse entities: Character '>' is reserved and must be escaped with the preceding '\'
```

**Expected behavior**
It seems that Telegram's Markdown does not support blockquotes. Maybe we can turn it into a code block or something else?

**Comment by skoropadas** [comment]
You are welcome, sorry I missed the last of your tickets.

Yes you are right Telegram's markdown doesn't support blockquotes, so I don't process them because if I start processing them then I need to process other things like tables etc. which are not possible.

Of course, there are several different solutions, for example, removing unsupported content or displaying it as code, but each of these solutions may be suitable for some library users and at the same time not suitable for others. Therefore, I would advise you to take a look at the [convert.js](https://github.com/skoropadas/telegramify-markdown/blob/master/lib/convert.js) file and create your own version in your project, adding your own handlers for elements that are not supported by Telegram's markdown.

**Comment by RainEggplant** [comment]
Thank you! That makes sense. But I think we can at least escape those characters so telegram will not raise an error and instead display them as-is?

> (From telegram's API doc)
>
> In all other places characters '_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!' must be escaped with the preceding character '\'.

**Comment by skoropadas** [comment]
Okay, since you're not the first person who asks this, I'll do the following:
I'll add an additional parameter that will allow you to escape unsupported tags and display them as-is. As a result, you'll be able to use the function like this:

```js
const escapedResult = telegramifyMarkdown(markdown, {}, true);
```

**Comment by skoropadas** [comment]
Ok I've changed my mind a bit, I've added more options, you can check them [here](https://github.com/skoropadas/telegramify-markdown#possible-options)

**Comment by RainEggplant** [comment]
Thanks!

**Comment by adriangalilea** [comment]
Hello,

[Telegram Markdown V2](https://core.telegram.org/bots/api#markdownv2-style) does include blockquotes now (and even code)

<img width="813" alt="Image" src="https://github.com/user-attachments/assets/3ff812f3-97dc-45be-a69d-f25690a74cf2" />

Is there any plan to support them?
